apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: create-image
spec:
  params:
  - name: image_name
    type: string
  workspaces:
  - name: source
  steps:
  - name: build-image
    image: gcr.io/kaniko-project/executor:debug
    workingDir: $(workspaces.source.path)/testing-test/fastapi
    command:
      - /kaniko/executor
    args:
      - --dockerfile=Dockerfile
      - --context=$(workspaces.source.path)/testing-test/fastapi
      - --destination="krotym2/fastapi"
