apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: deploy-image
spec:
  workspaces:
  - name: source
  steps:
  - name: create-yaml
    workingDir: $(workspaces.source.path)/kuber
    image: bash
    script: |
      cat  pod.yaml
      echo "5"
  - name: deploy-image
    workingDir: $(workspaces.source.path)/kuber
    image: lachlanevenson/k8s-kubectl
    command: ["kubectl"]
    args:
    - "apply"
    - "-f"
    - "pod.yaml"