apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: deploy-image
spec:
  workspaces:
  - name: source
  steps:
  - name: create-yaml
    workingDir: $(workspaces.source.path)/testing-test/kuber
    image: bash
    script: |
      cat deployment.yaml
      cat service.yaml
      cat ingress.yaml
      echo "---"
      echo "5"
  - name: deploy-image
    workingDir: $(workspaces.source.path)/testing-test/kuber
    image: lachlanevenson/k8s-kubectl
    script: |
      kubectl apply -f deployment.yaml
      kubectl apply -f service.yaml
      kubectl apply -f ingress.yaml
      echo "---"
      echo "6"

