apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: git-clone-my
spec:
  workspaces:
  - name: source
  params:
    - name: repo-url
      type: string
  steps:
  - name: check-files
    workingDir: $(workspaces.source.path)/fastapi
    image: bash
    script: |
      git clone $(params.repo-url)