apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: fastapi
spec:
  params:
  - name: image_name
    type: string
  - name: repo-url
    type: string
    description: The git repo URL to clone from.
  workspaces:
  - name: shared-data
  tasks:
  - name: fetch-source
    taskRef:
      name: git-clone
    workspaces:
    - name: output
      workspace: shared-data
    params:
    - name: url
      value: $(params.repo-url)
  - name: check-files
    taskRef:
      name: check-files
    workspaces:
    - name: source
      workspace: shared-data
  - name: create-image
    runAfter: ["fetch-source"]
    taskRef:
      name: create-image
    workspaces:
    - name: source
      workspace: shared-data
    params:
    - name: image_name
      value: $(params.image_name)
  - name: deploy-image
    runAfter: ["create-image"]
    taskRef:
      name: deploy-image
    workspaces:
    - name: source
      workspace: shared-data