apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: fastapi
spec:
  params:
  - name: repo-url
    type: string
    description: The git repo URL to clone from.
  - name: image-reference
    type: string
  workspaces:
    - name: shared-data
    - name: docker-login
  tasks:
  - name: fetch-source
    taskRef:
      name: git-clone-my
    workspaces:
    - name: source
      workspace: shared-data
    params:
    - name: repo-url
      value: $(params.repo-url)
  - name: check-files
    runAfter: ["fetch-source"]
    taskRef:
      name: check-files
    workspaces:
    - name: source
      workspace: shared-data
  - name: build-push
    runAfter: ["check-files"]
    taskRef:
      name: kaniko
    workspaces:
      - name: source
        workspace: shared-data
      - name: dockerconfig
        workspace: docker-login
    params:
    - name: IMAGE
      value: $(params.image-reference)
  - name: deploy-image
    runAfter: ["build-push"]
    taskRef:
      name: deploy-image
    workspaces:
    - name: source
      workspace: shared-data